---

- name: Attach an EBS Volume
  ec2_vol:
    instance: "{{ elasticluster.nodes[item].instance_id }}"
    aws_access_key: "{{ elasticluster.cloud.aws_access_key_id }}"
    aws_secret_key: "{{ elasticluster.cloud.aws_secret_access_key }}"
    region: "{{ elasticluster.cloud.aws_region }}"
    
    id: "{{ ebs_volume_id }}"
    device_name: "{{ ebs_device_name }}"
    delete_on_termination: "{{ ebs_delete_upon_termination }}"
    
  with_items: "{{ elasticluster.nodes | list }}"

