---
- hosts: coordinator
  gather_facts: yes
  become: no
  tasks:

  #O path aqui e absoluto. TODO no modulo converter para ansible_env.HOME+execution_dir
  - name: Creates directory
    file:
      path: "{{ directory }}"
      state: directory


  - name: Creates directory which will contain meta infos
    file:
      path: "{{ directory }}/.paramount-logs"
      state: directory
    register: folder_created
    ignore_errors: yes




########## Error handling

  - name: Remove job folder if it failed
    file:
      path: "{{ directory }}"
      state: absent
    when: folder_created.failed

  - name: Fail job creation if creation not successful
    fail:
      msg: "job creation failed"
    when: folder_created.failed