- name: create the execution path recursively if the same does not exist
  file:
    path: "{{ execution_dir }}"
    state: directory

- name: passing file
  synchronize:
    src: "{{ src_dir }}"
    dest: "~{{ execution_dir }}"