---   
- name: SPITS Playbook
  hosts: all
  gather_facts: yes
  tasks:    
  - name: "Including SPITS role"
    include_role:
      name: "spits-common"
      tasks_from: "{{ action }}"
    when: action in ['setup', 'job-create']
    
- name: SPITS TaskManager Playbook
  hosts: taskmanager
  gather_facts: no
  tasks:
  - include_role:
      name: "spits-common"
      tasks_from: "start-tm"
    when: action in ['start']

- name: SPITS Jobmanager Playbook
  hosts: jobmanager
  gather_facts: no
  tasks:
  - include_role:
      name: "spits-common"
      tasks_from: "start-jm"
    when: action in ['start']
    
  - include_role:
      name: "spits-common"
      tasks_from: "{{ action }}"
    when: action in ['job-status', 'job-copy']
