type-a:
    provider: aws-config-us-east-1
    login: login-ubuntu
    flavor: t2.micro
    image_id: ami-07d0cf3af28718ef8
    security_group: otavio-sg
       
type-b:
    provider: aws-config-us-east-1
    login: login-ubuntu
    flavor: t2.medium
    image_id: ami-07d0cf3af28718ef8
    security_group: otavio-secgroup
    boot_disk_size: 40
    # image_userdata: 
    # boot_disk_device: /dev/sda1
    # boot_disk_iops: io1
    # boot_disk_type: gp2
    # placement_group: XXX
