--- 
- hosts: all
  gather_facts: false
  tasks:
  - name: Reboot host and wait for it to restart  
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
  
- import_playbook: ../finish.yml
