---
- hosts: all
  gather_facts: no
  tasks:
    - name: Mark host as successfully configured
      shell: |
        echo 'done' > '{{ elasticluster.output_dir }}/{{ inventory_hostname }}.log'
      delegate_to: 'localhost'
      # this is necessary as we might not have/want superuser rights
      # where ElastiCluster is running
      become: no
