---

- name: Common setup for all hosts
  hosts: all
  gather_facts: yes
  pre_tasks:
    - name: Ensure the APT package cache is updated
      apt: 
        update_cache: yes
        cache_valid_time: 3600
      become: yes

- name: Run the playbook
  import_playbook: '{{ playbook_path }}'

- name: Report success on cluster creation
  hosts: all
  gather_facts: no
  tasks:
    - name: Mark host as successfully configured
      shell: |
        echo 'done' > '{{ elasticluster.output_dir }}/{{ inventory_hostname }}.log'
      delegate_to: 'localhost'
      become: no
